[package]
name = "dwelf"
version = "0.2.0"
edition = "2024"
description = "terrible image encoding library"
license = "Apache-2.0"
readme = "readme.md"

[features]
default = ["qoi"]
qoi = []

[dependencies]
